[package]
name = "carina-libgo"
version = "0.1.0"
edition = "2024"

[features]
default = ["sgf", "gtp"]
gtp = []
sgf = ["sgf-parse"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
sgf-parse = { version = "4.2.3", optional = true }
thiserror = "2.0.12"
